export type SampleSeededProduct = {
  name: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  costPrice: number;
  image: string;
  category: string;
  categorySlug: string;
  stock: number;
  isFeatured?: boolean;
  isTrending?: boolean;
  isHot?: boolean;
  isLimited?: boolean;
};

export const importedSampleProducts: SampleSeededProduct[] = [
  {
    name: "Birchwood Desk Organizer",
    description: "Handcrafted birch wood organizer for pens, cables, sticky notes, and everyday desk essentials.",
    price: 4800,
    compareAtPrice: 5600,
    costPrice: 2450,
    image: "/products/product_birchwood_organizer.jpg",
    category: "Eco Lifestyle",
    categorySlug: "eco-lifestyle",
    stock: 12,
    isFeatured: true,
  },
  {
    name: "Bamboo Cutlery Set",
    description: "Complete bamboo cutlery set for eco-conscious dining, travel kits, and reusable meal routines.",
    price: 3400,
    compareAtPrice: 3900,
    costPrice: 1700,
    image: "/products/product_bamboo_cutlery.jpg",
    category: "Bamboo Products",
    categorySlug: "bamboo-products",
    stock: 22,
    isTrending: true,
  },
  {
    name: "Oak Wall Shelf",
    description: "Floating oak shelf with a warm natural grain finish for decor, books, and soft lifestyle styling.",
    price: 7200,
    compareAtPrice: 8100,
    costPrice: 3920,
    image: "/products/product_oak_shelf.jpg",
    category: "Wooden Decor",
    categorySlug: "wooden-decor",
    stock: 8,
    isFeatured: true,
  },
  {
    name: "Walnut Serving Board",
    description: "Elegant walnut board made for serving fruit, snacks, breads, and intimate hosting moments.",
    price: 5800,
    compareAtPrice: 6500,
    costPrice: 3040,
    image: "/products/product_walnut_board.jpg",
    category: "Bamboo Products",
    categorySlug: "bamboo-products",
    stock: 10,
    isHot: true,
  },
  {
    name: "Linen Napkin Set",
    description: "Set of four soft organic linen napkins in calming earth tones for premium table settings.",
    price: 2900,
    compareAtPrice: 3400,
    costPrice: 1360,
    image: "/products/product_linen_napkins.jpg",
    category: "Eco Lifestyle",
    categorySlug: "eco-lifestyle",
    stock: 18,
  },
  {
    name: "Cork & Wood Coasters",
    description: "Sustainable coasters that combine recycled cork and wood textures for everyday entertaining.",
    price: 2200,
    compareAtPrice: 2600,
    costPrice: 940,
    image: "/products/product_coasters.jpg",
    category: "Wooden Decor",
    categorySlug: "wooden-decor",
    stock: 25,
  },
  {
    name: "Ceramic Candle Vessel",
    description: "Hand-poured candle in a reusable ceramic vessel with warm wood notes and a calm ambient glow.",
    price: 3800,
    compareAtPrice: 4300,
    costPrice: 1680,
    image: "/products/product_candle_vessel.jpg",
    category: "Wooden Decor",
    categorySlug: "wooden-decor",
    stock: 14,
    isTrending: true,
  },
  {
    name: "Maple Utensil Holder",
    description: "Maple wood holder that keeps spoons, spatulas, and kitchen tools organized with a cleaner counter look.",
    price: 4400,
    compareAtPrice: 5000,
    costPrice: 2120,
    image: "/products/product_utensil_holder.jpg",
    category: "Bamboo Products",
    categorySlug: "bamboo-products",
    stock: 11,
  },
  {
    name: "Teak Storage Box",
    description: "Durable teak box with a timeless finish for tea bags, jewelry, chargers, and shelf organization.",
    price: 6500,
    compareAtPrice: 7400,
    costPrice: 3440,
    image: "/products/product_storage_box.jpg",
    category: "Handmade Crafts",
    categorySlug: "handmade-crafts",
    stock: 7,
    isLimited: true,
  },
  {
    name: "Ash Picture Frame",
    description: "Minimal ash wood frame that highlights natural grain while keeping photos and art beautifully grounded.",
    price: 2800,
    compareAtPrice: 3200,
    costPrice: 1180,
    image: "/products/product_picture_frame.jpg",
    category: "Wooden Decor",
    categorySlug: "wooden-decor",
    stock: 16,
  },
  {
    name: "Pine Desk Lamp",
    description: "Warm desk lamp with a pine base and linen shade for productive, soft-lit corners at home.",
    price: 5600,
    compareAtPrice: 6300,
    costPrice: 2960,
    image: "/products/product_desk_lamp.jpg",
    category: "Eco Lifestyle",
    categorySlug: "eco-lifestyle",
    stock: 9,
    isHot: true,
  },
  {
    name: "Woven Storage Basket",
    description: "Hand-woven basket that blends soft texture and practical storage for bedrooms, entryways, and living rooms.",
    price: 4100,
    compareAtPrice: 4700,
    costPrice: 1920,
    image: "/products/product_woven_basket.jpg",
    category: "Handmade Crafts",
    categorySlug: "handmade-crafts",
    stock: 13,
    isTrending: true,
  },
  {
    name: "Beeswax Candle Set",
    description: "Set of three pure beeswax candles with a natural honey scent and a warm, premium evening glow.",
    price: 2400,
    compareAtPrice: 2800,
    costPrice: 960,
    image: "/products/product_candle_set.jpg",
    category: "Wooden Decor",
    categorySlug: "wooden-decor",
    stock: 20,
  },
];
